# Generated by Django 5.2.10 on 2026-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ad_title',
            field=models.CharField(blank=True, help_text='Short ad title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bachelors_allowed',
            field=models.BooleanField(default=True, help_text='Are bachelors allowed?'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1, help_text='Number of bathrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='bhk',
            field=models.IntegerField(default=1, help_text='Number of BHKs (Bedrooms)'),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('NORTHEAST', 'North-East'), ('NORTHWEST', 'North-West'), ('SOUTHEAST', 'South-East'), ('SOUTHWEST', 'South-West')], default='NORTH', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('FULLY_FURNISHED', 'Fully Furnished')], default='SEMI_FURNISHED', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='super_built_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Super built area in sqft', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(default=1, help_text='Total floors in the building'),
        ),
    ]
