# Generated by Django 5.2.10 on 2026-02-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_year',
            field=models.IntegerField(blank=True, help_text='Year the property was built', null=True),
        ),
    ]
