# Generated by Django 5.2.10 on 2026-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_property_built_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plan_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Date when the plan expires', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], default='basic', help_text='Selected plan type', max_length=20),
        ),
    ]
