# Generated by Django 5.2.10 on 2026-03-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
