# Generated by Django 5.2.10 on 2026-03-01 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_maintenancerequest_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')])),
                ('title', models.CharField(help_text='Brief title for your feedback', max_length=200)),
                ('comment', models.TextField(help_text='Share your experience with RentEase')),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('is_approved', models.BooleanField(default=True, help_text='Admin approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Feedback',
                'verbose_name_plural': 'Website Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
