# Generated by Django 5.2.10 on 2026-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_websitefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times this property has been viewed'),
        ),
    ]
