# Generated by Django 5.2.10 on 2026-03-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_property_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapplication',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentalapplication',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='property',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='RentalApplication',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
